// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZZpvJ8U9C9uCTTr3XZkEtHq_fNEfAxs',
    appId: '1:659178872085:web:415f92c92103c28136dd1c',
    messagingSenderId: '659178872085',
    projectId: 'lookism-hairstudio-booking',
    authDomain: 'lookism-hairstudio-booking.firebaseapp.com',
    storageBucket: 'lookism-hairstudio-booking.firebasestorage.app',
    measurementId: 'G-MG0DGBZ7NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlSWqYCFac1nYFovMGIkmhzw0FyJ3sNE',
    appId: '1:659178872085:android:ae1a5b8d323b382f36dd1c',
    messagingSenderId: '659178872085',
    projectId: 'lookism-hairstudio-booking',
    storageBucket: 'lookism-hairstudio-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbvljfv7WdWVLG9PkLe5nv_0s8LPEne0',
    appId: '1:659178872085:ios:73fcb85078f404f536dd1c',
    messagingSenderId: '659178872085',
    projectId: 'lookism-hairstudio-booking',
    storageBucket: 'lookism-hairstudio-booking.firebasestorage.app',
    iosBundleId: 'com.example.lookismHairstudioBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVbvljfv7WdWVLG9PkLe5nv_0s8LPEne0',
    appId: '1:659178872085:ios:73fcb85078f404f536dd1c',
    messagingSenderId: '659178872085',
    projectId: 'lookism-hairstudio-booking',
    storageBucket: 'lookism-hairstudio-booking.firebasestorage.app',
    iosBundleId: 'com.example.lookismHairstudioBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZZpvJ8U9C9uCTTr3XZkEtHq_fNEfAxs',
    appId: '1:659178872085:web:c3b62840becf7a3b36dd1c',
    messagingSenderId: '659178872085',
    projectId: 'lookism-hairstudio-booking',
    authDomain: 'lookism-hairstudio-booking.firebaseapp.com',
    storageBucket: 'lookism-hairstudio-booking.firebasestorage.app',
    measurementId: 'G-QWCKCSHG7M',
  );
}
